
print('-----------------specify char---------------------')
print(r"print( 'C:\some\name') ===> "+"C:\some\name")
print(r"print( r'C:\some\name') ===> "+ r"C:\some\name")
print('"Isn\'t," she said.')
print('-----------------String multiple---------------------')
print(r"3 * 'un' + 'ium' ===> "+3 * 'un' + 'ium')
print('-----------------String array---------------------')
word = 'Python'
print("word = 'Python'")
print("print(word[0]) ==> "+word[0])
print("print(word[5]) ==> "+word[5])
print("print(word[-1]) ==> "+word[-1])
print("print(word[-3]) ==> "+word[-3])
print("print(word[-6]) ==> "+word[-6])
print("print(word[0:2]) ==> "+word[0:2])
print("print(word[2:5]) ==> "+word[2:5])
print("print(word[2:]) ==> "+word[2:])
print("print(word[:2]) ==> "+word[:2])
print("print(word[4:42]) ==> "+word[4:42])
print("print(word[42:]) ==> "+word[42:])
